services:
  streamlitsrv:
    build: ./streamlitsrv
    ports:
      - "8502:8502"
    volumes:
      - .:/app
      - ./streamlitsrv:/app
      - upload_data:/app/data
    working_dir: /app
    depends_on:
      - ocr
      - doclayout
    networks:
      - logios-network

  doclayout:
    build: ./dlayout
    restart: on-failure
    ports:
      - "8602:8602"
    volumes:
      - .:/app
      - ./dlayout:/app
      - upload_data:/app/data
    working_dir: /app
    depends_on:
      - ocr
    networks:
      - logios-network

  ocr:
    build: ./ocr
    volumes:
      - .:/app
      - ./ocr:/app
      - upload_data:/app/data
    working_dir: /app
    networks:
      - logios-network

volumes:
  upload_data:
  app:


networks:
  logios-network:
    driver: bridge
    name: logios-network
