#version: '3.8'

services:
  streamlitsrv:
    build: ./streamlitsrv
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./streamlitsrv:/app         
      - upload_data:/app/data
    working_dir: /app
    depends_on:
      - ocr
  doclayout:
    build: ./dlayout 
    restart: on-failure
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - upload_data:/app/data
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DEBUG=1
  ocr:
    build: ./ocr
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - upload_data:/app/data

volumes:
  upload_data:
  app: